### ISSUE TITLE
подписка на задачу

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#102]
реализовать кнопку "подписаться/отписаться" на задачу. автор подписывается автоматом.
если есть подписка - все что пишется в комменты (сами комменты, смены статусов и пр) отправляются на почту тем, кто подписался.

согласуй плз со мной механику решения.

**Comment by romannep** [comment]
юзерам добавить email -ы, 
отправлять через nsp.utils.sendEmail
````
        from: params.from,
        to: params.mailTo,
        subject: params.subj,
        text: params.text
````

**Comment by romannep** [comment]
* кнопка Подписаться/Отписаться
* таблица наблюдателей с возможностью добавления по юзернейму

**Comment by dputilov** [comment]
* Реализован механизм подписки на задачу - список пользователей, с возможностью добавления по логину. Кнопки "Подписаться/Отписаться" для текущего пользователя
* Реализована отправка новых комментариев к задаче. 
Для отправки нужно:
- В Пользователях добавить e-mail, на который нужно отправлять уведомления.
- В Проектах добавить e-mail для поля "От"
* При изменении исполнителя - добавляется комментарий "Назначен исполнитель ..."
* Реализована процедура me.afterSaveData  (вызов в Form.form - saveData)
