### ISSUE TITLE
новый список Все задачи (обновление ссылок)

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#103]
отображать все задачи всех доступных проектов

если фильтр по проекту не указан, то обращаемся к спец. серверной процедуре, которая делает запросы по каждому доступному проекту и соединяет выборки в одну.

**Comment by romannep** [comment]
Корректируем: делаем идеологически верно - выборка одна, за счет хранения избыточной информации.

Определим следующий синтаксис: в серверном классе сущности может быть определено поле links такого вида:
````
me.links = {
author: {},
project: {
    fields:["author","users"]
    }
}
````
Каждое поле объекта links указывает о том, что у сущности есть одноименная ссылка, которую надо обновлять/дополнять по следующим правилам
- Если у ссылки указано поле fields то в саму сущность в поле со ссылкой помимо title и _id должны попасть поля указанные в массиве.
- Каждый раз при записи сущности, перебираются ее ссылки и если ссылка указана (есть _id) происходит вытягивание из базы документа по этой ссылке и формирование самой ссылки:
  - В ссылку записывается объект {_id, title}
  - Объект ссылки дополняется полями указанными в fields

Свойство links определяется в классе сущности, код обработки свойства происходит в классе Entity в методе put.

В указанном примере произойдет следующее:
- вне зависимости от того, какие доп поля придут с клиента в поле author в базу запишется
````
...
author: {_id:'someId', title: 'someTitle'}
...
````
- вне зависимости от того, какие поля придут с клиента в поле project в базу запишется
````
...
project: {_id:'someId', title: 'someTitle',author: {...}, users: [...]}
...
````

**Comment by dputilov** [comment]
Обновление ссылок задается структурой вида (по _id обновляются поля title и перечисленные в массиве fields):

    me.links = {
        author: {
            entity:"User",
            fields:["login"]
        },
        executor: {
            entity:"User"
        },
        project: {
            entity:"Project",
            fields:["author","users"]
            }
    };

**Comment by dputilov** [comment]
Выполнено
1. Список задач "Все" - отображаются все задачи, доступные текущему пользователю:
- все задачи где текущий пользователь либо исполнитель, либо автор
- все задачи по доступным проектам 

2. Реализовано обновление ссылок. Структура описывается в классе сущности в параметре links. 
Обновление ссылок происходит в функции put в классе Entity
