### ISSUE TITLE
приложение Мастер - концепция

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#117]
На первом этапе мы решаем следующие задачи:

1. Переход от ручного проектирования сущностей к проектированию через приложение.
2. Включение выборок БД в репозиторий.

Результат проектирования сущностей в приложении - это сохраненные документы в базе данных. На основании этих документов некий код будет генерировать файлы классов. Ясно, что этот процесс будет односторонним - т.е. из файлов классов записи в БД не восстановишь (можно отдельный парсер написать, но смысла не вижу). Все сущности у нас глобальны - т.е. у каждого разработчика должна быть актуальная база данных с описанием сущностей. Поэтому необходимо реализовать экспорт/импорт документов - описаний сущностей в файлы и хранить эти файлы в едином репозитории (для начала - включить в git).

Общая концепция работы с генерированным кодом такая: наше приложение генерирует файлы-классы, которые:

* являются основными файлами классов (т.е. теми файлами классов, с которыми работают приложения)
* являются недоступными для изменения разработчиком

Включение произвольного кода в классы осуществляется через механизм пост-наследования: при необходимости внесения такого кода создается специальный класс с неким пре(пост)фиксом, в который разработчик вносит весь необходимый код, и этот класс добавляется в пост-родители основному классу.

**Comment by dputilov** [comment]
предлагаю организовать следующую структуру системных файлов
ИмяСущности.Base - основной файл описания сущности, имя сущности, структура реквизитов (?), родители (пост/пред) - генерируется автоматически на основании Параметров сущности, задаваемых пользователем в визуальной среде разработки ("конфигураторе")
ИмяСущности.ServerModule- модуль серверного кода сущности - содержит процедуры и функции, выполняемые на сервере, полностью пишется разработчиком в среде разработки "как есть"
подключается к Base-файлу

ИмяСущности.Form.ИмяФормы.Base - содержит заголовок формы, родителей, описание элементов формы, генерируется автоматически на основании визуального "конструктора формы"
ИмяСущности.Form.ИмяФормы.Module - модуль формы - содержит процедуры и функции, выполняемые на клиенте, полностью пишется разработчиком в среде разработки "как есть"
подключается к Base-файлу формы

Форм может быть произвольное количество, базовый файл описания сущности - один.
Все файлы относящиеся к одной сущности физически хранятся в одном каталоге с названием "ИмяСущности"

**Comment by romannep** [comment]
Есть пара вопросов на подумать: 

1. Таблица элементов формы. У нас разные элементы и у многих есть "индивидуальные" поля-свойства. Получается что при редактировании строки (а строка - это конкретный элемент формы) у нас будут разные наборы полей для разного вида элементов формы. Надо думать как реализовать.
2. Задание элементов (колонок) какой нибудь таблицы. В общем случае в сущности может быть несколько таблиц. И на каждую надо задать список колонок/полей. Надо думать как реализовать.
