### ISSUE TITLE
Сделать расширение FileBase - файловый движок

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#126]
Расширение будет подключаться к сущности Entity и заменять базовые методы get,put,view на методы работы с файловой системой.

Примеры чтения / записи файлов в 
./nsp.js staticFile
./classes/EntityDefinition.js make
Чтение списка файлов - для функции view: ./classes/FileManager.js readDir (надо не переписывать, а воспользоваться - me.app.getEntity("FileManager").readDir() . предварительно в файле приложения добавив сущность через me.addEntity("FileManager"))

Все файлы - сущности хранить в корне в папке classSources: подпапка - имя сущности, файлы в подпапке - сами сущности. Именовать файлы сущностей как "EntityId###EntityTitle" - т.е. в имени файла через разделитель будут указаны поля _id и title, к примеру - "From.list###Шаблон формы списка"

**Comment by dputilov** [comment]
Выполнено
Реализовано как расширение FileBase к Entity (me.extensions.Entity = ["FileBase"];)
