### ISSUE TITLE
Доработка голосовалки

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#129]
Доступ - только зареганым. При попытке оценки проверять - есть ли от юзера оцена в таблице, если есть - то оценку не менять.

**Comment by romannep** [comment]
вторая подзадача: открывать результаты оценок только после голосования. Т.е. если человек за отзыв не проголосовал, то он не видит как его оценили другие пользователи.
Соответсттвенно неавторизованные вообще не видят оценок отзыва.

**Comment by romannep** [comment]
все выше - реализовано. есть две подзадачи.

1. Изменить принцип голосования за полезность: голосование должно быть по пятибальной шкале - от 1 до 5. Соответственно в значение должно выводится среднее.

2. Возможность "воздержаться" - чтоб человеку показалась оценка, но голосовать он уже не мог. Для голосования по интересности можно сделать как голосование с нулевым показателем. По полезности - надо подумать (с нулевым нельзя - средняя будет падать)

**Comment by motoowl** [comment]
Всё выше - готово.

Новая задача - сделать расчёт среднего значения оценки средствами базы данных (убрать из кода).
