### ISSUE TITLE
MASTER: Программные модули сущности и формы сущности

### ISSUE THREAD

**Issue by dputilov** [romannep/nsp2#130]
Реализовать ввод, генерацию и подключение программных модулей сущности.
На первоначальном этапе реализовать Серверный и Клиентский модуль.
В мастере модули отображаются в виде текстового поля textarea. 
Текст модуля задается вручную разработчиком конфигурации.  
По кнопке make на каждый модуль создается свой отдельный файл с текстом модуля.
<Сущность>Module.js - серверный
<Сущность><ИмяФормы>Module.js - клиентский
Программные модули подключаются к сущности и форме сущности как родители.

**Comment by romannep** [comment]
по серверному - понятно. а вот Клиентский модуль - это что? По сути - таких модулей может быть много - на каждую форму по одному.

**Comment by dputilov** [comment]
Клиентский - модуль формы.  Для каждой формы - отдельный модуль.

**Comment by dputilov** [comment]
Добавлены модуль сущности и модули для каждой создаваемой формы.
Модули вставляются непосредственно в файл сущности и файлы форм.

Предлагаю обсудить, есть ли вообще необходимость вынесения программных модулей в отдельный файл?
