### ISSUE TITLE
MASTER: Формы сущности

### ISSUE THREAD

**Issue by dputilov** [romannep/nsp2#133]
У каждой сущности может быть сколько угодно форм.
Формы задаются таблицей. Для каждой формы задаются параметры
- Имя формы 
- Представление 
- Шаблон формы (выбирается из списка шаблонов)
- Родители, расширения 
- Таблица реквизитов с привязкой к данным (как это сейчас реализовано для сущности)
- Модуль кода

Для каждой формы создается отдельный файл описания формы и подключаемый к нему файл программного модуля формы.

**Comment by romannep** [comment]
Тут нюансы.
У разных форм по идее будет разный набор реквизитов.
То что сейчас реализовано в самой сущности - это по сути форма редактирования элемента: мы задаем имя реквизита и его элемент управления (текстовое поле, флаг и т.п.). Для формы списка указание типов редактирования реквизитов неактуально - там же таблица.

Нужно подойти немного с другой стороны: форма списка по сути - та же форма, только у нее один основной элемент формы - это таблица, с привязкой к данным (в которой отображаются элементы сущности). Т.е. при создании формы списка мы просто добавим элемент формы - "Таблица" и будем задавать в ней колонки с привязкой к данным. Но сейчас среди доступных элементов формы нет элемента "Таблица" - надо продумывать как его добавить.

**Comment by dputilov** [comment]
Выполнено

Список форм хранится в таблице. 
Для каждой формы задаются свои параметры и реквизиты формы 

Форма списка также задается как обычная форма с элементом - таблица.

Генерация файлов:
- Для сущности создается файл описания сущности с именем [Имя сущности].js
- Для каждой формы создается свой файл с именем [Имя сущности].[Имя формы].js
