### ISSUE TITLE
пробить шаблоны по умолчанию через настройки

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#157]
Цель: при создании форм, сущностей чтоб шаблоны для генерации были заполнены по умолчанию
- создать настройки
- при создании элементов заполнять шаблоны из настроек - они лежат на клиенте в сессии

**Comment by romannep** [comment]
В меню внизу есть "Настройки системы", там по текстовому идентификатору можно указывать настройки. Добавляем строку, выбираем тип - ОК. Еще раз открываем - значение нужного типа - можно устанавливать

Вот пример, когда при открытии формы устанавливаются настройки

```
    function addIncome(rowData) {
        var formParams = {
            container: nsp.cm.createContainer(true),
            parentForm: me,
            data: {
                main: {
                    content: {
                        date: rowData.date,
                        driver: rowData.driver
                    }
                }
            }
        };
        nsp.session.settings.moneyIncomeArticle_default && (formParams.data.main.content.moneyIncomeArticle = nsp.session.settings.moneyIncomeArticle_default);
        
        nsp.openForm({ form: "CarUsage.addIncome", formParams: formParams });
    }

```
Но наверно лучше зашивать в форму сразу в датасет
```
me.data.main.content.someField = nsp.session.settings.someSetting
```

**Comment by romannep** [comment]
а вообще - нужны ли нам эти реквизитына форме?
предлагаю их вообще убрать, а в коде получать шаблоны из настроек.

док system_settings в мастере надо бы перевести на файловый режим.

**Comment by dputilov** [comment]
Добавлены настройки для шаблонов гл. меню, сущности и форм сущностей.
Выбор шаблона оставлен на форме, для возможности изменить шаблон (например для списков, выбора и т.д.)
