### ISSUE TITLE
авторизация и редирект на нее

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#16]
Сделать чего нибудь типа формы входа в админку. Ну и чтоб был редирект на эту форму при неавторизованном доступе. 
Тут не торопиться - надо продумать целиком процедуру работы с админской частью

**Comment by romannep** [comment]
Предложение пока сделать влоб. 
На клиенте определим, что nsp.user будет хранить инфу о текущем пользователе. 
В глоб функцию которая вызывается постоянно - nsp.openForm - встроим проверку наличия этого поля. Если его нет - редирект на страницу авторизации.
Страницу авторизации можно захаркодить в static/nsp-auth.html
Ну и надо допилить сервер: чтоб как то с сервера нам приходил объект user

**Comment by dputilov** [comment]
1. вызов api_call вынесен в auth.html
2. в сессию записывается объект user
3. включена поддержка режима alladmin
