### ISSUE TITLE
Права на публичные классы

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#17]
у cms у нас есть классы у которых есть неавторизованный доступ по некоторым функциям (get,view). по умолчанию - наша проверка прав не разрешит чтение.

надо реализовать чтоб разрешала. без дублирования кода.

**Comment by romannep** [comment]
делаем два доп класса PublicRead и PublicView

**Comment by dputilov** [comment]
Выполнено. Протестировано на классе Project

**Comment by romannep** [comment]
надо протестить на классе User - добавить оба класса и тогда заглушка в штатном контроле прав будет не нужна.
И что за право - start ?

**Comment by dputilov** [comment]
start - изначально хотел сделать особый режим при входе в систему, чтобы не разрешать права на User для всех, т.е. вижу 2 пути решения:

1. особый режим при входе, когда разрешено чтение на класс user
2. всем разрешить право на чтение класса user

я так понимаю сейчас мы идем по 2му пути?

**Comment by dputilov** [comment]
1. Подключил публичные права на User
2. Убрал заглушку и режим start
3. Протестировал вход  в систему - авторизация работает
