### ISSUE TITLE
Единая точка входа в клиента разных приложений

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#42]
Сейчас по сути что nsp-client.html что nsteamer.html - файлы полностью одинаковые за исключением id подключаемого меню.
Договоримся, что основное меню имеет идентификатор menu_admin_main. Пропишем именно его в nsp-client.html 

Ну и у себя в БД создадим док с таким идентификатором. И теперь отдельные файлы входа в приложения не нужны будут.

**Comment by romannep** [comment]
т.е. вход у всех приложений будет один - nsp-client.html

**Comment by dputilov** [comment]
Выполнено
