### ISSUE TITLE
обновлять id в форме при сохранении нового

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#48]
Имеем:
открываем форму создания нового документа (задачи, проекта и т.п.), заполняем поля, тыкаем "Сохранить" 5 раз - создается пять новых документов
Надо:
Первый тык - создается документ, последующие - обновляется
Причина:
В новой форме в data нет поля _id - при сохарнении без _id субд сама генерит его и делает новый документ. Надо после сохранения обновлять _id в данных формы

**Comment by romannep** [comment]
решение инкапсулировать в saveData

**Comment by dputilov** [comment]
В saveData реализовано присвоение _id новому объекту , а также изменение текущей версии объекта _rev
