### ISSUE TITLE
Форма простых комментов

### ISSUE THREAD

**Issue by romannep** [romannep/nsp2#58]
Сами комменты - линейный массив, с объектами - дата+время, автор, текст коммента
На форме будут:
* собственно сами комменты - логичней их сделать новым отдельным элементом. но для начала для теста можно и таблицу вывести
* поле для ввода нового комментария и кнопка "комментировать"

форму комментов подключить к задаче и к проекту.

**Comment by dputilov** [comment]
Реализовано подключение "комментариев" к "задачам" (через пост наследование)
Классы комментариев:
"Comments.plain"
"Element.commentTable"
