### ISSUE TITLE
Выбор пользователей в проекте

### ISSUE THREAD

**Issue by dputilov** [romannep/nsp2#86]
1. Добавление пользователей к проекту сделать по логину.
Пользователь вводит логин в текстовое поле, при нажатии "Добавить" осуществляется поиск и добавление пользователя с таким логином.
2. В задаче при выборе исполнителя, список доступных пользователей брать из проекта

**Comment by dputilov** [comment]
2. Проект, по которому формируется список доступных пользователей, берется из БД. Т.е. задача должна быть предварительно записана

**Comment by romannep** [comment]
1. В выборке в переборе по юзерам при незаполненном юзере может вылезтти ошибка в условии и функция не отработает
2. Выборка идеет по проектам, поэтому она должна быть присоединена к сущности проект
3. решение с keyPath слишком узкое, да и требование сохранить задачу перед  выбором исполнителя тоже не логичное. сделать более универсально:
в форме есть функция beforeLoadData - мы можем в элементе ее задавать, а внутри reference передавать в форму. т.е. без доп. изменений реализовать логику динамического фильтра

**Comment by romannep** [comment]
4. (это как вариант, не обязательно) список юзеров есть в самом проекте - т.е. вместо создания доп выборки можно было просто подтянуть документ с проектом и в таблицу вывести его таб часть с юзерами.
